### PR TITLE
Add SNI support

### PR DESCRIPTION
**Pull request by Enrico204**
Hi all,

I've added SNI support to SSL connections ;-)

PS: I've also added some gradle files to ignore list; these files are created by Intellij IDEA and I think that they may be ignored. Is that right?

Enrico

### CODE REVIEW

**Comment by ennswi** [comment]
@Enrico204 
if I use this implementation. I got the message "The target server failed to respond".

**Comment by Enrico204** [comment]
@ennswi I did some tests yesterday and I had no issues. I'm testing again this code, maybe I forgot something ;-)

PS: I've tested the app with Davical and SNI-enabled host. I'll test a non-SNI host to see if this code has issues with that (it shouldn't have)

**Comment by Enrico204** [comment]
@ennswi I've fixed in my repository on last commit. Should I create another pull request?

**Comment by ennswi** [comment]
Yes.

**Pull request merged**
