### PR TITLE
Fix for Google Calendar /dav/ endpoint

### PR DESCRIPTION
**Pull request by matthesrieke**
Hi ennswi,

I have encountered similar behaviour is described in #8. This PR should fix it for the moment. I have created a Google specific workaround, but in a smooth way using a DiscoveryStrategy interface that intercepts requests to google.com.

Also note that this works for the moment but Google has deprecated the old https://www.google.com/calendar/dav/* endpoint. I think aCalDav does not support OAuth2.0 atm, right? But in the long term we should think about using the [new API](https://developers.google.com/google-apps/calendar/caldav/v2/guide).

best
Matthes

### CODE REVIEW

**Comment by SoerenEilenberger** [comment]
Hi Matthes,  

thanks for this!

If this helps, I 'd like to point out that the old version of caldav sync adapter 1.80 still works with Google, with the remaining problem of one way Sync though (reason for 1.81 in which google doesn't work)... 

cheers Sören

**Comment by SoerenEilenberger** [comment]
I just updated to acaldav 0.04. If the changes are included, it didn't work...

**Comment by SoerenEilenberger** [comment]
It says wrong url

**Comment by matthesrieke** [comment]
Yes, it is not included in aCalDav yet. if you trust me, you could install a recent debug release and check if it works. Note that debug and release build will exist in parallel on your device.

https://www.dropbox.com/s/yjn41f4grjnjq5x/ACalDAV-debug-0.0.4.apk?dl=0

**Comment by matthesrieke** [comment]
i just noticed that syncing has one issue: if you delete an event on the google calendar web client and synchronize the calendar on the device, the deleted event is still present on the device. I will look into that.

**Comment by SoerenEilenberger** [comment]
Hi Matthes, I trust you, but have a probably dumb question... 

It says it couldn't parse the apk... I tried to install the apk with the packet installer. Was that wrong?

**Comment by SoerenEilenberger** [comment]
Hi Matthes, 

Did you find time to fix the delete issue yet? I still couldn't install the apk from your Dropbox by the way... 

Have nice weekend! 
Sören

**Pull request merged**
